Event detail a pi
BharatShukla30/neighborly-node pull request #106
Opened 2024-06-30 14:37 UTC by amansd25

2024-07-01 08:47 UTC, BharatShukla30 requested changes

2024-07-01 08:47 UTC, BharatShukla30 commented on controllers/eventController.js
> +const { error } = require('winston');
what is this for?

2024-07-01 08:47 UTC, BharatShukla30 commented on controllers/eventController.js
> +        activityLogger.info("event Id recived");
which event id is received? spelling issue with received

2024-07-01 08:47 UTC, BharatShukla30 commented on controllers/eventController.js
> +            eventId: event.eventid,
user id and user's display picture should also been given

2024-07-01 08:47 UTC, BharatShukla30 commented on controllers/eventController.js
> +            location: event.location,
multimedia should also be there

2024-07-02 14:14 UTC, amansd25 commented on controllers/eventController.js
> +const { error } = require('winston');
it has the same working as activity logger and error logger so as we already have activity logger and error logger in our code so we don't need const { error } = require('winston');

2024-07-02 16:12 UTC, amansd25 commented on controllers/eventController.js
> +        activityLogger.info("event Id recived");
the event which we call

2024-07-02 16:16 UTC, amansd25 commented on controllers/eventController.js
> +            location: event.location,
added

2024-07-05 13:11 UTC, merged